site_name: "Mister Y's Lab Notes"
site_description: 'What is happening in the lab!'
site_author: 'Alan Yorinks'
site_url: 'https://andre601.ch/blog'

copyright: |
  &copy; Alan Yorinks

theme:
  name: 'material'

features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.annotate

nav:
  - Blog:
      - blog/index.md
plugins:
  - search
  - blog:
      blog_dir: blog
